README.md

The SmartyStreets US Reverse Geocoding API takes lat/long coordinates and transforms them into addresses. SmartyStreets does it super fast and super accurate.

Adding SmartyStreets in the Geo section.

---

README.md

This PR adds a section for environment variables management.

Add Environment Variables Section

---

README.md

Zigi tagline update

---

README.md

Adding a new category for (micro) service orchestration. Including 3 main tools for the orchestration of services in polyglot and cloud-native architectures.

Adding new category "Orchestration"

---

README.md

DocRaptor's link in README is broken, this PR fixes it :)

Fix DocRaptor's link

---

README.md

Resources to read more about it:
https://depot.dev/docs#when-to-use-depot
https://depot.dev/docs/integrations/github-actions
https://depot.dev/#benchmarks

Add Depot to CI/CD tools

---

README.md

"Bump.sh helps you build a branded single source of truth, documenting and cataloging your APIs. Teams now have a reference point for building and consuming APIs whether with OpenAPI, Swagger, or AsyncAPI."

Add bump.sh

---

README.md

Add BoxyHQ to Authentication & Identity

Add BoxyHQ Enterprise SSO

---

README.md

This commit introduces a new category: **Security**
It includes 4 developer-first products:
- https://bearer.com - Static application security testing (SAST) tool for JavaScript and Ruby stacks.
- https://gitguardian.com/ - Real-time GitHub activity scanner.
- https://snyk.io/ - Vulnerability scanner for code, dependencies, containers, and infrastructure as code.
- https://socket.dev/ - Detect and block open-source supply chain attacks.
And fixes Issue #64.

Add new category: Security

---

README.md

Add Meilisearch

---

README.md

Add Imitate Email

---

README.md

Add PlaceKit

---

README.md

https://magicbell.com/
Thanks!

Add MagicBell

---

README.md

https://www.vessel.dev/
Thanks!

Add Vessel

---

README.md

Add Increase

---

OUTCAST.md
README.md

In #84 we wanted to look into Scanbot SDK. its current [pricing page](https://scanbot.io/pricing/) is a request form, which doesn't match the [guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md).

Move Scanbot SDK to OUTCAST.md

---

README.md

Hey 👋 
I've added Unleash in the Feature Flags category, it's an Open-source Feature Flagging service that enables you to control your releases.
Website: https://getunleash.io
Let me know if everything is okay! 👌 
Thanks!

Add Unleash

---

README.md

This commit introduces a new category: **Automation**
It includes 2 developer-first products:
- https://n8n.io - Free and source-available fair-code licensed workflow automation tool.
- https://trigger.dev/ - Open-source platform to create workflows from APIs, on a schedule or on demand.
And fixes Issue #82.
Thanks!

Add new category: Automation

---

README.md

Adding Aserto.com to the authentication and identity section. Aserto cloud-native SaaS that provides developers with an easy way to add fine-grained access control to their web applications. It works with every identity provide and framework, and is the only solution on the market that support every authorization model out of the box (RBAC, ABAC, PBAC, ReBAC and any other BAC :-))
Thanks!

Add Aserto

---

README.md

Added you, just check the text and link is good.
P.S. It's the #100 PR 🥳

Update README.md - Add flo

---

README.md

Add Infisical

---

README.md

Add Resend

---

README.md

Add Image-Charts

---

README.md

OpenCage provides a forward and reverse geocoding API based on open data
URL: https://opencagedata.com
Thanks!

Add OpenCage to GEO

---

README.md

Add Better Stack
betterstack.com
Thanks!

Add Better Stack

---

README.md

[Quix](https://quix.io/)
Thanks!

adding quix.io to deployment hosting

---

README.md

[https://github.com/firecamp-dev/firecamp]
Firecamp is added in the testing category. 
Thanks!

Add Firecamp

---

README.md

**Website**: https://revert.dev
**Pricing page:**  https://revert.dev/#Pricing
Thanks!

Add Revert

---

README.md

Add CometLLM

---

README.md

https://deploybot.com/
Thanks!

Add DeployBot

---

README.md

Add airbrake.io

---

README.md

* [browserless](https://browserless.io) 
Thanks!

Add browserless.io

---

README.md

Add new category: Backend-as-a-Service

---

README.md

Add Octomind

---

README.md

https://www.highlight.io/
Thanks!

Add highlight.io

---

CONTRIBUTING.md
README.md

Add GitHub Stars to COSS products

---

README.md

Add Panora.dev

---

README.md

Add Flatfile

---

README.md

Add Apidog

---

README.md

Add YepCode

---

README.md

https://www.abstra.io/
Thanks!

Add Abstra

---

README.md

Add Cycle.io

---

README.md

* [DatoCMS](https://www.datocms.com/) - API-based CMS.
Thanks!

Add DatoCMS

---

README.md

* [Bytescale](https://bytescale.com/) - File storage and processing APIs.
Thanks!

Add Bytescale

---

README.md

Add Stytch

---

README.md

Add Neon Postgres

---

README.md

https://statsig.com/
- [X ] The homepage clearly states that the product is for developers.
- [ X] The product is available now and requires payment.
- [ X] The PR has a descriptive title -- e.g., `Add {Product}`, not `Update README.md`.
- [ X] The new submission isn't a duplicate.
- [ X] The entry has a description, is sorted alphabetically, and ends with a full stop.
Thanks!

Add Statsig

---

README.md

Adding Pixee to Code Quality and Security sections
Thanks!

Add Pixee to Security

---

README.md

Add CodSpeed to Testing

---

README.md

Add Pagerly

---

README.md

Add Docusign APIs

---

README.md

[https://www.marscode.com/](https://www.marscode.com/)
Thanks!

Add MarsCode

---

README.md

[Zenrows](https://www.zenrows.com/)
Thanks!

Add ZenRows

---

README.md

Added MojoAuth CIAM solution provider
https://mojoauth.com/
Thanks!

Add MojoAuth

---

README.md

Helicone is an LLM observability and monitoring tool for developers building AI apps.
Thanks!

Add Helicone AI

---

README.md

Add lilbots.io

---

README.md

[www.heybounce.io](www.heybounce.io)
Thanks!

Add Heybounce

---

README.md

Add Nango to "Integrations"

---

README.md

Fix typo to **with** instead of **wiht**
Thanks!

Fix typo (Ubiq)

---

README.md

Added Webscrapinghq to readme

---

README.md

Add Locize

---

README.md

Add Propexo

---

README.md

Add GoCodeo

---

README.md

[OneCompiler](https://onecompiler.com/)
Thanks!

Add OneCompiler to IDEs section

---

README.md

Sherlo - Visual testing and review tool for React Native Storybook.
https://sherlo.io
Thanks!

Add Sherlo

---

README.md

[https://corsfix.com](https://corsfix.com)
Thanks!

Add Corsfix

---

README.md

https://signatureapi.com
Thanks!

Add SignatureAPI

---

README.md

Adding 2 new categories suggested in #191 and #192:
- Gen UI
- AI Coding

Add categories
